title: Lex Groente - DEVELOPMENT
email: mick@localheroesonline.com
description: DEVELOPMENT De plek om voordelige groente te kopen! Met een groot assortiment en een lage prijs staan we ook wel bekend als de 50cent kraam
url: http://127.0.0.1:4000 # the base hostname & protocol for your site, e.g. http://example.com
image_url: http://127.0.0.1:4000
cloudimg: https://axajvrynho.cloudimg.io/v7/
environment: development

# tracking events
google_analytics: NOWHERE
mixpanel-project-token: 624a5eaf9d84caf4c6c5af9a45a08a4a # development

sass:
    sass_dir: _sass
    style: uncompressed